import React from "react";
import { ColorInput, Switch, TextInput } from "@mantine/core";
import { type SettingsMarkup } from "~/renderer/scenes/Settings";

export const settingsMarkup: SettingsMarkup = [
    // {
    //     name: "Reopen last book on startup.",
    //     description: "",
    //     hoverDescription: "Whether or not app will open last read book on startup.",
    //     tabHeading: "",
    //     tab: "App Settings",
    //     section: "Startup",
    //     Input: Switch,
    //     defaultValue: "true",
    //     canBeDisabled: false,
    //     Icon: () => <span>test</span>,
    // },
    // {
    //     name: "ss",
    //     description: "ss",
    //     hoverDescription: "ss",
    //     Input: ColorInput,
    //     Icon: () => <span>test</span>,
    //     canBeDisabled: false,
    //     defaultValue: "#fff",
    //     tabHeading: "",
    //     tab: "",
    //     section: "",
    // },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        name: "ONE",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        Icon: () => <></>,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        name: "TWO",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        Icon: () => <></>,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Files & Links",
        section: "Unnamed",
        name: "THREE",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        Icon: () => <></>,
        canBeDisabled: false,
    },
    {
        tabHeading: "Core Plugins",
        tab: "Files & Links",
        section: "Unnamed",
        name: "FOUR",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        Icon: () => <></>,
        canBeDisabled: false,
    },
];
