import React from "react";
import { ColorInput, Switch, TextInput } from "@mantine/core";
import { type SettingsMarkup } from "~/renderer/scenes/Settings";
import { IconAdjustments } from "@tabler/icons-react";

export const settingsMarkup: SettingsMarkup = [
    {
        label: "Reopen last book on startup.",
        description: "",
        placeholder: "Huh",
        hoverDescription: "Whether or not app will open last read book on startup.",
        tabHeading: "afsd",
        tab: "App Settings",
        section: "Startup",
        Input: Switch,
        defaultChecked: false,
        canBeDisabled: false,
        SectionIcon: () => <span>t</span>,
    },
    {
        label: "ss",
        description: "ss",
        placeholder: "TEtxt",
        hoverDescription: "ss",
        Input: TextInput,
        SectionIcon: () => <span>t</span>,
        canBeDisabled: false,
        defaultValue: "#fff",
        tabHeading: "sd",
        tab: "asdf",
        section: "asdf",
    },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        SectionIcon: IconAdjustments,
        label: "ONE",
        placeholder: "COLOR",
        description: "",
        defaultValue: "",
        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        SectionIcon: IconAdjustments,
        label: "TWO",
        placeholder: "Coflr",
        description: "",
        hoverDescription: "",
        defaultValue: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Files & Links",
        section: "Unnamed",
        SectionIcon: IconAdjustments,
        label: "THREE",
        placeholder: "colr",
        description: "",
        hoverDescription: "",
        defaultValue: "",

        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Core Plugins",
        tab: "Files & Links",
        section: "Unnamed",
        SectionIcon: IconAdjustments,
        label: "FOUR",
        placeholder: "COLCOUR",
        description: "",
        defaultValue: "",

        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
];
