import React from "react";
import { ColorInput, Switch, TextInput } from "@mantine/core";
import { type SettingsMarkup } from "~/renderer/scenes/Settings";
import { IconAdjustments } from "@tabler/icons-react";

export const settingsMarkup: SettingsMarkup = [
    {
        name: "Reopen last book on startup.",
        description: "",
        hoverDescription: "Whether or not app will open last read book on startup.",
        tabHeading: "afsd",
        tab: "App Settings",
        section: "Startup",
        Input: Switch,
        defaultValue: "true",
        canBeDisabled: false,
        SectionIcon: () => <span>t</span>,
    },
    {
        name: "ss",
        description: "ss",
        hoverDescription: "ss",
        Input: TextInput,
        SectionIcon: () => <span>t</span>,
        canBeDisabled: false,
        defaultValue: "#fff",
        tabHeading: "sd",
        tab: "asdf",
        section: "asdf",
    },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        SectionIcon: IconAdjustments,
        name: "ONE",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Editor",
        section: "General",
        SectionIcon: IconAdjustments,
        name: "TWO",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Options",
        tab: "Files & Links",
        section: "Unnamed",
        SectionIcon: IconAdjustments,
        name: "THREE",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
    {
        tabHeading: "Core Plugins",
        tab: "Files & Links",
        section: "Unnamed",
        SectionIcon: IconAdjustments,
        name: "FOUR",
        description: "",
        hoverDescription: "",
        Input: ColorInput,
        canBeDisabled: false,
    },
];
