# ref: https://sevic.dev/notes/electron-forge-publish-github/

name: Release app
on:
    workflow_dispatch:
jobs:
    build:
        environment: CI
        strategy:
            matrix:
                os: [
                        # { name: "windows", image: "windows-latest" },
                        # { name: "linux", image: "ubuntu-latest" },
                        { name: "macos", image: "macos-13" },
                    ]
            fail-fast: true
        runs-on: ${{ matrix.os.image }}
        steps:
            - name: Github checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - run: npm install
            # ref: https://github.com/LinusU/node-appdmg/issues/234#issuecomment-2002410428
            - name: Fix appdmg GHA mac runner error 1
              if: matrix.os.name == 'macos'
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Fix appdmg GHA mac runner error 2
              if: matrix.os.name == 'macos'
              run: |
                  python3 -m pip install setuptools --break-system-packages
                  npm install -g appdmg@0.6.6
            - name: Publish app
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOOKORD_RELEASE_TOKEN }}
              run: npm run publish
