# ref: https://sevic.dev/notes/electron-forge-publish-github/

name: Release app
on:
    workflow_dispatch:
jobs:
    build:
        environment: CI
        strategy:
            matrix:
                os: [
                        # { name: "windows", image: "windows-latest" },
                        # { name: "linux", image: "ubuntu-latest" },
                        { name: "macos", image: "macos-11" },
                    ]
            fail-fast: true
        runs-on: ${{ matrix.os.image }}
        steps:
            - name: Github checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm install
            - name: Publish app
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOOKORD_RELEASE_TOKEN }}
              run: npm run publish
